Movie.create(title:"Gone Girl",image:"images/movie1.jpg", rating: "3", releaseDate: "2014-02-22")
Movie.create(title:"The Good Life",image:"images/movie2.jpg", rating: "4", releaseDate: "2014-06-24")
Movie.create(title:"The Hero of Color City",image:"images/movie3.jpg", rating: "0", releaseDate: "2014-11-23")
Movie.create(title:"Guardians of the Galaxy",image:"images/movie4.jpg", rating: "5", releaseDate: "2014-07-01")
Movie.create(title:"The Drop",image:"images/movie5.jpg", rating: "0", releaseDate: "2017-12-01")
Movie.create(title:"If I Stay",image:"images/movie6.jpg", rating: "0", releaseDate: "2018-01-01")